networks:
  default:
    name: private-net
    external: true

name: cloud-emulator

services:
  floci:
    image: floci/floci:latest
    container_name: floci
    deploy:
      resources:
        limits:
          cpus: '0.50'     # Maximum 50% of a single CPU core
          memory: 512M    # Maximum 512 Megabytes of RAM
        reservations:
          cpus: '0.25'     # Guaranteed minimum 25% of a CPU core
          memory: 256M
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      FLOCI_STORAGE_MODE: hybrid

  floci-ui:
    image: floci/floci-ui:latest
    container_name: floci-ui
    deploy:
      resources:
        limits:
          cpus: '0.50'     # Maximum 50% of a single CPU core
          memory: 512M    # Maximum 512 Megabytes of RAM
        reservations:
          cpus: '0.25'     # Guaranteed minimum 25% of a CPU core
          memory: 256M
    ports:
      - "4500:4500"
    environment:
      FLOCI_ENDPOINT: http://floci:4566
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    depends_on:
      - floci